# Generated by Django 4.1.3 on 2022-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='especialidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
