# Generated by Django 4.1.3 on 2022-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='Nombre_Especialidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
